CREATE TABLE timetable (
TRAIN_NUMBER INT PRIMARY KEY NOT NULL,
START_TIME DATE NOT NULL,
END_TIME DATE NOT NULL,
STOPPAGES INT NOT NULL,
PANTRY_CAR BOOLEAN NOT NULL,
FOREIGN KEY(TRAIN_NUMBER) REFERENCES trains(TRAIN_NUMBER)
);